### ISSUE TITLE
#include <omp.h> On   MAC ?????  

### ISSUE THREAD

**Issue by anthonyyuan** [freesouls/face-alignment-at-3000fps#7]
Users/anthonyyuan/desktop/src/face-alignment-at-3000fps-master 2/main.cpp:10:10: fatal error: 
      'omp.h' file not found
**#include <omp.h>**
         ^
1 error generated.
make[2]: *** [CMakeFiles/application.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/application.dir/all] Error 2
make: *** [all] Error 2

**Comment by gicheonkang** [comment]
@anthonyyuan hi, I have a same problem
How did you resolve this problem?
